#ifndef FAST_CAPTURE_DEF_H
#define FAST_CAPTURE_DEF_H

#include <stdint.h>

#define FAST_CAPTURE_NOEXCEPT noexcept
#define FAST_CAPTURE_CALL __stdcall
#ifdef _MSC_VER
#define FAST_CAPTURE_EXPORT __declspec(dllexport)
#else
#define FAST_CAPTURE_EXPORT __attribute__((visibility("default")))
#endif

#define FAST_CAPTURE_STR_IMPL(x) #x
#define FAST_CAPTURE_STR(x) FAST_CAPTURE_STR_IMPL(x)

#define FAST_CAPTURE_NAME FastCapture
#define FAST_CAPTURE_NAMESPACE namespace FAST_CAPTURE_NAME
#define FAST_CAPTURE ::FAST_CAPTURE_NAME
#define FASTCAPTURE ::FAST_CAPTURE_NAME

#define FAST_CAPTURE_ERROR_TYPE_SUCCESS 0
#define FAST_CAPTURE_ERROR_TYPE_DEFAULT 1
#define FAST_CAPTURE_ERROR_TYPE_WIN32 2
#define FAST_CAPTURE_ERROR_TYPE_GLEW 3

typedef struct FastCaptureErrorCode1__
{
    uint16_t error_code;
    uint16_t error_code_ex_type;
    uint32_t error_code_ex;
} FastCaptureErrorCode;

#define FAST_CAPTURE_S_OK 0

inline FastCaptureErrorCode FastCaptureMakeSuccessValue()
{
    return FastCaptureErrorCode{
        FAST_CAPTURE_S_OK,
        FAST_CAPTURE_ERROR_TYPE_SUCCESS,
        0};
}

#define FAST_CAPTURE_E_WAIT_INJECT_FAILED 2
#define FAST_CAPTURE_E_WAIT_INJECT_THREAD_TIMEOUT 3
#define FAST_CAPTURE_E_CREATE_INJECT_THREAD_FAILED 4
#define FAST_CAPTURE_E_CREATE_REMOTE_MEMORY_FAILED 5
#define FAST_CAPTURE_E_INIT_INJECT_DLL_FAILED 6
#define FAST_CAPTURE_E_INIT_INJECT_DLL_TIMEOUT 7
#define FAST_CAPTURE_E_GET_INIT_INJECT_DLL_RESULT_FAILED 8
#define FAST_CAPTURE_E_WAIT_INIT_READ_PIXELS_THREAD_TIMEOUT 9
#define FAST_CAPTURE_E_WAIT_INIT_READ_PIXELS_THREAD_FAILED 10
#define FAST_CAPTURE_E_GET_SELF_DLL_HANDLE_FAILED 11
#define FAST_CAPTURE_E_CREATE_READ_PIXELS_THREAD_INIT_EVENT_FAILED 12
#define FAST_CAPTURE_E_CREATE_READ_PIXELS_THREAD_RUN_COMMAND_EVENT_FAILED 13
#define FAST_CAPTURE_E_CREATE_READ_PIXELS_THREAD_FAILED 14
#define FAST_CAPTURE_E_CREATE_SHARED_CAPTURE_DESCRIPTOR_FAILED 15
#define FAST_CAPTURE_E_CREATE_SHARED_CAPTURE_DESCRIPTOR_MAP_OF_VIEW_FAILED 16
#define FAST_CAPTURE_E_READ_PIXELS_THREAD_NOT_AVAILABLE 17
#define FAST_CAPTURE_E_GL_BASIC_WINDOW_WAIT_THREAD_INIT_TIMEOUT 18
#define FAST_CAPTURE_E_READ_PIXELS_THREAD_CREATE_SHARED_CAPTURE_IMAGE_FAILED 19
#define FAST_CAPTURE_E_READ_PIXELS_THREAD_CREATE_SHARED_CAPTURE_IMAGE_MAP_OF_VIEW_FAILED 20
#define FAST_CAPTURE_E_GL_BASIC_WINDOW_WAIT_THREAD_INIT_FAILED 21
#define FAST_CAPTURE_E_WAIT_RESULT_UNEXPECTED 22
#define FAST_CAPTURE_E_COPY_INJECT_DLL_INIT_DATA_FAILED 23
#define FAST_CAPTURE_E_CREATE_GL_BASIC_WINDOW_CLASS_FAILED 24
#define FAST_CAPTURE_E_GET_EXE_INSTANCE_FAILED 25
#define FAST_CAPTURE_E_CREATE_GL_BASIC_WINDOW_FAILED 26
#define FAST_CAPTURE_E_GET_GL_BASIC_WINDOW_DC_FAILED 27
#define FAST_CAPTURE_E_CHOOSE_PIXEL_FORMAT_FAILED 28
#define FAST_CAPTURE_E_SET_PIXEL_FORMAT 29
#define FAST_CAPTURE_E_GL_BASIC_WINDOW_WGL_CREATE_CONTEXT_FAILED 30
#define FAST_CAPTURE_E_GL_BASIC_WINDOW_WGL_MAKE_CURRENT_FAILED 31
#define FAST_CAPTURE_E_GL_BASIC_WINDOW_WGL_SHARE_LISTS_FAILED 32
#define FAST_CAPTURE_E_GL_BASIC_WINDOW_GLEW_INIT_FAILED 33
#define FAST_CAPTURE_E_GL_BASIC_WINDOW_CREATE_THREAD_INIT_EVENT_FAILED 34
#define FAST_CAPTURE_E_GL_BASIC_WINDOW_CREATE_INIT_THREAD_FAILED 35
#define FAST_CAPTURE_E_READ_PIXELS_THREAD_INVOKE_FAILED 36
#define FAST_CAPTURE_E_INVALID_ARGUMENT 87
// 259(STILL_ACTIVE)是保留的

#endif
